DROP TABLE IF EXISTS public.watchlist CASCADE;
DROP TABLE IF EXISTS public.group_movies CASCADE;
DROP TABLE IF EXISTS public.group_members CASCADE;
DROP TABLE IF EXISTS public.groups CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.favorites CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE public.users (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(50) NOT NULL UNIQUE,
    email character varying(255) NOT NULL UNIQUE,
    password character varying(255) NOT NULL
);

CREATE TABLE public.favorites (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    movie_id integer NOT NULL
);

CREATE TABLE public.reviews (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    movie_id integer NOT NULL,
    review_text text NOT NULL,
    rating smallint NOT NULL CHECK (rating >= 1 AND rating <= 5),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.groups (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    owner_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE public.group_members (
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    group_id integer NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
    status character varying(20) NOT NULL DEFAULT 'pending',
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE public.group_movies (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
    movie_id integer NOT NULL
);

CREATE TABLE public.watchlist (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    movie_id integer NOT NULL
);